### ISSUE TITLE
Add delete by link

### ISSUE THREAD

**Issue by Hajto** [sschneider1207/ExCloudinary#1]
Please consider adding feature deleteing image by it's link.

**Comment by jschneider1207** [comment]
A link includes the picture's public id, doesn't it?  If it does I'd prefer to just keep this a minimal wrapper around their api.

**Comment by Hajto** [comment]
Ow actually it does. The issue can be safely closed.

PS: It would use some more examples. Especially with transformations. Maybe not like Cloduinary docs extensive but at least some.
