### ISSUE TITLE
Build fails on heroku

### ISSUE THREAD

**Issue by Hajto** [sschneider1207/ExCloudinary#3]
```
Will use the following versions:
* Stack cedar-14
* Erlang 18.2.1
* Elixir 1.2.3
```

And stacktrace:

```
remote: == Compilation error on file lib/ex_cloudinary/client.ex ==
remote: ** (CompileError) lib/ex_cloudinary/client.ex:50: invalid literal nil in
 <<>>
remote:     (elixir) src/elixir_bitstring.erl:149: :elixir_bitstring.build_bitst
r/4
remote:     lib/ex_cloudinary/client.ex:50: (module)
remote:
remote: could not compile dependency :ex_cloudinary, "mix compile" failed. You c
an recompile this dependency with "mix deps.compile ex_cloudinary", update it wi
th "mix deps.update ex_cloudinary" or clean it with "mix deps.clean ex_cloudinar
y"
remote:
remote:  !     Push rejected, failed to compile elixir app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to kpsz.
remote:
To https://git.heroku.com/kpsz.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/kpsz.git'
```

**Comment by sds88** [comment]
Do you have your configs set up properly?  That line is referring to:
`defp append_secret(signature), do: signature <> @api_secret`

`@api_secret` being `nil` implies it is being compiled without the config entry for your api key secret.

**Comment by Hajto** [comment]
config :ex_cloudinary,
  name: System.get_env("cloud_name"),
  api_key: System.get_env("cloud_key"),
  api_secret: System.get_env("cloud_key_secret")

and all values are provided through config vars panel on heroku

**Comment by Hajto** [comment]
Ouch heroku messed up. I hardcoded everything to config and it lives.
But please. Do a url config option. Because that's what heroku provide automagically.
cloudinary://key:secret@name

**Comment by jschneider1207** [comment]
@Hajto Just wanted to update you, I just pushed a version `0.2.0` that changes the config `name` to `cloud_name` as per your suggestion.  I kept the other two because that is what Cloudinary calls them under your `Account Details` on the Dashboard page

**Comment by Hajto** [comment]
I actually meant to enable config by one connection string formatted as seen above.
